### ISSUE TITLE
Back | VA-Sensor | Emulator | MainServiceConfig

### ISSUE THREAD

**Issue by a-givertzman** [a-givertzman/va-sensor-emulator#4]
- [ ] Service to be created from [this template](https://github.com/a-givertzman/rust-sal-sync/blob/master/src/services/service/service_template.rs)
- [ ] config: 
```yaml
service MainService MainService-1:
    sampl-freq: 100.0      # Hz
    buf-size: 512
    signal:
        # freq: amplitude, [phase]
        #  Hz     R.U.      rad
        - 100.0:  100.11
        - 220.0:  220.22
```
Pseudo-code sketch
```rust
/// The configuration of the MainService
/// - sampl_freq - sampling frequency, number of samples to be generated per second
/// - buf_size - number of samples to be sent in the single UDP message
/// - freq & buf_size wi;; determine the number of UDP messages to be sent per second
struct MainServiceConf {
    pub name: Name,
    pub sampl_freq: f64,
    pub buf_size: u64,
    ///               freq, amplitude, phase
    pub signal: Vec<(f64, f64, f64)>,
}
impl MainServiceConf {
    pub fn new(parent: impl Into<String>, conf_tree: &mut ConfTree) -> Self {
         ...
    }
}
```
